name: SSH Login and run scriptss

on:
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

          
      - name: Execute Package Build Outputs Script
        run: |
          plink.exe -ssh -batch ibmuser@10.10.1.180 -P 2222 -pw s3cure "export JAVA_HOME=/usr/lpp/java/J8.0_64; export PATH=\$JAVA_HOME/bin:/Rocket/rsusr/ported/bin:\$PATH; echo Logged in successfully; /dbbibm/dbbv2.0.2/bin/groovyz /u/ibmuser/dbb/Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy --workDir /u/ibmuser/dbbwazi1/dbb-zappbuild/build/out/APP4/build.20240902.134123.302 --tarFileName APP4.tar --application APP4 --addExtension --branch main --generateWaziDeployAppManifest --versionName rel-1.0.0 --verbose"
